-- 테이블 삭제
DROP TABLE PROCEEDING_TBL;
DROP TABLE PROJECT_TBL;
DROP TABLE EMPLOYEE_TBL;
DROP TABLE DEPARTMENT_TBL;

-- 부서 테이블 생성
CREATE TABLE DEPARTMENT_TBL (
    DEPT_NO         VARCHAR2(15 BYTE) NOT NULL,
    DEPT_NAME       VARCHAR2(30 BYTE),
    DEPT_LOCATION   VARCHAR2(50 BYTE),
    CONSTRAINT PK_DEPARTMENT PRIMARY KEY(DEPT_NO)
);

-- 사원 테이블 생성
CREATE TABLE EMPLOYEE_TBL (
    EMP_NO      NUMBER NOT NULL,
    DEPT_NO     VARCHAR2(15 BYTE),
    POSITION    CHAR(10 BYTE),
    NAME        VARCHAR2(15 BYTE),
    HIRE_DATE   DATE,
    SALARY      NUMBER,
    CONSTRAINT PK_EMP_NO PRIMARY KEY(EMP_NO),
    CONSTRAINT FK_DEPT_NO FOREIGN KEY(DEPT_NO) REFERENCES DEPARTMENT_TBL(DEPT_NO) ON DELETE SET NULL -- 부서가 없어지면 사원의 부서 정보만 NULL 처리된다. 
 );   

-- 프로젝트 테이블 생성
CREATE TABLE PROJECT_TBL (
    PJT_NO NUMBER NOT NULL,
    PJT_NAME VARCHAR2(30 BYTE),
    BEGIN_DATE DATE,
    END_DATE DATE,
    CONSTRAINT PK_PJT_NO PRIMARY KEY(PJT_NO)
);
    
-- 프로젝트진행 테이블 생성
CREATE TABLE PROCEEDING_TBL (
    PCD_NO NUMBER NOT NULL,
    EMP_NO NUMBER,
    PJT_NO NUMBER,
    PJT_STATE NUMBER NOT NULL,
    CONSTRAINT PK_PCD_NO PRIMARY KEY(PCD_NO),
    CONSTRAINT FK_EMP_NO FOREIGN KEY(EMP_NO) REFERENCES EMPLOYEE_TBL(EMP_NO) ON DELETE SET NULL,
    CONSTRAINT FK_PJT_NO FOREIGN KEY(PJT_NO) REFERENCES PROJECT_TBL(PJT_NO)  ON DELETE SET NULL
);